model_path: ./checkpoints/drink_model.pt
conf_threshold: 0.8
iou_threshold: 0.8
classes:
  - beer_tiger
  - bottle
  - can
  - cocacola
  - cocacola_light
  - green_tea
  - pepsi
  - red_bull
  - revive_lemon_salt
  - revive_regular
  - strawberry_sting
